version: "3.8"

services:

  grafana:
    image: "grafana/grafana:latest"
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    networks:
      - heritage
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - heritage

  zipkin:
    image: openzipkin/zipkin
    mem_limit: 700m
    ports:
      - "9411:9411"
    networks:
      - heritage

  config-server:
    image: heritage/config-server:latest
    mem_limit: 700m
    ports:
      - "8888:8888"
    networks:
      - heritage

  discovery-server:
    image: heritage/discovery-server:latest
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - heritage
    depends_on:
      - config-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  company_mongo_db:
    image: mongo:latest
    container_name: company_mongo_db
    restart: always
    ports:
      - 27017:27017

  company-service:
    image: heritage/company-service:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - heritage
    depends_on:
      - config-server
      - discovery-server
      - company_mongo_db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  auth_mongo_db:
    image: mongo:latest
    container_name: auth_mongo_db
    restart: always
    ports:
      - 27027:27017

  auth-service:
    image: heritage/auth-service:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - heritage
    depends_on:
      - config-server
      - discovery-server
      - auth_mongo_db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  stock_mongo_db:
    image: mongo:latest
    container_name: stock_mongo_db
    restart: always
    ports:
      - 27037:27017

  stock-service:
    image: heritage/stock-service:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
      - heritage
    depends_on:
      - config-server
      - discovery-server
      - stock_mongo_db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  api-gateway:
    image: heritage/api-gateway:latest
    mem_limit: 700m
    ports:
      - "1000:1000"
    networks:
      - heritage
    depends_on:
      - config-server
      - discovery-server
      - stock-service
      - company-service
      - auth-service
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 180s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

networks:
  heritage:
