version: "3.8"

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data:rw # Persistence data

  logstash:
    image: docker.elastic.co/logstash/logstash:7.2.0
    ports:
      - "25826:25826"
      - "5044:5044"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro # Pipeline configuration
    restart: on-failure
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    ports:
      - "5601:5601"
    restart: on-failure
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.2.0
    volumes:
      - ./filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro # Configuration file
      - /var/lib/docker/containers:/var/lib/docker/containers:ro # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro # Additional information about containers
      - ./filebeat/data:/usr/share/filebeat/data:rw # Persistence data
    user: root # Allow access to log files and docker.sock
    restart: on-failure
    depends_on:
      - logstash

  zipkin:
    image: openzipkin/zipkin
    mem_limit: 700m
    ports:
      - "9411:9411"
    networks:
      - heritage

  config-server:
    image: heritage/config-server:latest
    mem_limit: 700m
    ports:
      - "8888:8888"
    networks:
      - heritage

  discovery-server:
    image: heritage/discovery-server:latest
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - heritage
    depends_on:
      - config-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  company_mongo_db:
    image: mongo:latest
    container_name: company_mongo_db
    restart: always
    ports:
      - 27017:27017

  company-service:
    image: heritage/company-service:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - heritage
    depends_on:
      - config-server
      - discovery-server
      - company_mongo_db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  auth_mongo_db:
    image: mongo:latest
    container_name: auth_mongo_db
    restart: always
    ports:
      - 27027:27017

  auth-service:
    image: heritage/auth-service:latest
    mem_limit: 700m
    ports:
      - "9090:9090"
    networks:
      - heritage
    depends_on:
      - config-server
      - discovery-server
      - auth_mongo_db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  stock_mongo_db:
    image: mongo:latest
    container_name: stock_mongo_db
    restart: always
    ports:
      - 27037:27017

  stock-service:
    image: heritage/stock-service:latest
    mem_limit: 700m
    ports:
      - "7070:7070"
    networks:
      - heritage
    depends_on:
      - config-server
      - discovery-server
      - stock_mongo_db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  api-gateway:
    image: heritage/api-gateway:latest
    mem_limit: 700m
    ports:
      - "1000:1000"
    networks:
      - heritage
    depends_on:
      - config-server
      - discovery-server
      - stock-service
      - company-service
      - auth-service
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 180s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

networks:
  heritage:
